name: FactionsPro
author: Tethered_
description: A Plugin For Easily Managing Factions
version: 1.5b2
main: FactionsPro\FactionMain
api: [1.12.0]
commands:
  f:
    description: use /f help for all parameters
    permission: f.command
permissions:
  f.command:
    default: true
    description: "Allow use of all faction commands"
  f.override:
    default: op
    description: "Allows op users to override factions"
